# Link Validation Notebook

This notebook checks every link in the MkDocs `docs/` folder and reports whether links are valid or broken. It focuses on internal Markdown links and URL syntax validation.

In [1]:
import re
from pathlib import Path
import urllib.parse
import requests
import pandas as pd

root = Path('.').resolve()
docs_root = root / 'docs'
md_files = sorted(docs_root.rglob('*.md'))

link_re = re.compile(r'!?\[[^\]]*\]\(([^)]+)\)')
exclude_prefixes = ('mailto:', 'javascript:')

## Load URL List

Collect internal Markdown links from `docs/` and prepare them for validation.

In [2]:
links = []
for md in md_files:
    text = md.read_text(encoding='utf-8', errors='ignore')
    for match in link_re.finditer(text):
        target = match.group(1).strip()
        if not target or target.startswith('#'):
            continue
        links.append({'source': str(md.relative_to(root)), 'target': target})

links_df = pd.DataFrame(links)
links_df.head(20)

,source,target
0,docs\Condensed Matter Physics.md,Physics%20Note/CMP/Lattice%20Type.md
1,docs\Condensed Matter Physics.md,Physics%20Note/CMP/Lattice%20structure.md
2,docs\Condensed Matter Physics.md,Physics%20Note/CMP/Reciprocal%20Lattice.md
3,docs\Condensed Matter Physics.md,Physics%20Note/CMP/X-ray%20Diffraction.md
4,docs\Condensed Matter Physics.md,Physics%20Note/CMP/Bonding.md
5,docs\Condensed Matter Physics.md,Physics%20Note/CMP/Lattice%20vibration.md
6,docs\Condensed Matter Physics.md,Physics%20Note/CMP/Heat%20Capacity.md
7,docs\Condensed Matter Physics.md,Physics%20Note/Debye%20Model%201.md
8,docs\Condensed Matter Physics.md,Physics%20Note/Metal%201.md
9,docs\Condensed Matter Physics.md,Physics%20Note/Metal%20II.md
10,docs\Condensed Matter Physics.md,Physics%20Note/Properties%20of%20free%20electr...
11,docs\Condensed Matter Physics.md,Physics%20Note/Band%20Theory.md
12,docs\Condensed Matter Physics.md,Physics%20Note/Bloch's%20theorem.md
13,docs\Condensed Matter Physics.md,Physics%20Note/Introduction%20and%20Bonding.md
14,docs\Condensed Matter Physics.md,Physics%20Note/Length%20Scales%20and%20Time%20...
15,docs\Condensed Matter Physics.md,Physics%20Note/Lattices%20and%20Symmetry%20Ope...
16,docs\Condensed Matter Physics.md,Physics%20Note/Reading%20Character%20Tables.md
17,docs\Condensed Matter Physics.md,Physics%20Note/Selection%20Rules%20and%20Prope...
18,docs\Condensed Matter Physics.md,Physics%20Note/Crystallographic%20Space%20Grou...
19,docs\Condensed Matter Physics.md,Physics%20Note/Scattering%20Techniques.md

## Validate URL Format

Check the syntax of each link before attempting network requests.

In [3]:
def normalize_target(target):
    if '#' in target:
        target = target.split('#', 1)[0]
    return target

valid_links = []
for row in links_df.to_dict('records'):
    target = row['target']
    parsed = urllib.parse.urlparse(target)
    if parsed.scheme and parsed.scheme not in ('http', 'https'):
        valid_links.append({**row, 'valid_format': False, 'reason': 'unsupported scheme'})
        continue
    valid_links.append({**row, 'valid_format': True, 'reason': ''})

valid_df = pd.DataFrame(valid_links)
valid_df.head(20)

,source,target,valid_format,reason
0,docs\Condensed Matter Physics.md,Physics%20Note/CMP/Lattice%20Type.md,True,
1,docs\Condensed Matter Physics.md,Physics%20Note/CMP/Lattice%20structure.md,True,
2,docs\Condensed Matter Physics.md,Physics%20Note/CMP/Reciprocal%20Lattice.md,True,
3,docs\Condensed Matter Physics.md,Physics%20Note/CMP/X-ray%20Diffraction.md,True,
4,docs\Condensed Matter Physics.md,Physics%20Note/CMP/Bonding.md,True,
5,docs\Condensed Matter Physics.md,Physics%20Note/CMP/Lattice%20vibration.md,True,
6,docs\Condensed Matter Physics.md,Physics%20Note/CMP/Heat%20Capacity.md,True,
7,docs\Condensed Matter Physics.md,Physics%20Note/Debye%20Model%201.md,True,
8,docs\Condensed Matter Physics.md,Physics%20Note/Metal%201.md,True,
9,docs\Condensed Matter Physics.md,Physics%20Note/Metal%20II.md,True,
10,docs\Condensed Matter Physics.md,Physics%20Note/Properties%20of%20free%20electr...,True,
11,docs\Condensed Matter Physics.md,Physics%20Note/Band%20Theory.md,True,
12,docs\Condensed Matter Physics.md,Physics%20Note/Bloch's%20theorem.md,True,
13,docs\Condensed Matter Physics.md,Physics%20Note/Introduction%20and%20Bonding.md,True,
14,docs\Condensed Matter Physics.md,Physics%20Note/Length%20Scales%20and%20Time%20...,True,
15,docs\Condensed Matter Physics.md,Physics%20Note/Lattices%20and%20Symmetry%20Ope...,True,
16,docs\Condensed Matter Physics.md,Physics%20Note/Reading%20Character%20Tables.md,True,
17,docs\Condensed Matter Physics.md,Physics%20Note/Selection%20Rules%20and%20Prope...,True,
18,docs\Condensed Matter Physics.md,Physics%20Note/Crystallographic%20Space%20Grou...,True,
19,docs\Condensed Matter Physics.md,Physics%20Note/Scattering%20Techniques.md,True,

## Send HTTP Requests to Each Link

Validate external links by sending HTTP requests and capturing response status codes.

In [4]:
external_links = [row for row in valid_links if urllib.parse.urlparse(row['target']).scheme in ('http', 'https')]
results = []
for row in external_links:
    target = row['target']
    try:
        resp = requests.head(target, allow_redirects=True, timeout=10)
        results.append({**row, 'status_code': resp.status_code, 'reason': ''})
    except Exception as exc:
        results.append({**row, 'status_code': None, 'reason': str(exc)})

results_df = pd.DataFrame(results)
results_df.head(20)

,source,target,valid_format,reason,status_code
0,docs\Physics Note\CMP\Reciprocal Lattice.md,https://www.researchgate.net/post/What-is-the-...,True,,403
1,docs\Physics Note\Master's degree.md,https://www.manchester.ac.uk/study/postgraduat...,True,,200
2,docs\Physics Note\Master's degree.md,https://www.manchester.ac.uk/study/masters/cou...,True,,200
3,docs\Physics Note\Master's degree.md,https://www.dur.ac.uk/departments/academic/phy...,True,,403
4,docs\Physics Note\Master's degree.md,https://www.ox.ac.uk/admissions/graduate/cours...,True,,403
5,docs\Physics Note\Master's degree.md,https://www.ntu.edu.sg/spms/about-us/physics/g...,True,,200
6,docs\Physics Note\RLI Astronomy (Mass of Jupit...,https://doi.org/10.1111/j.1365-2966.2011.18947.x,True,,403

## Report Link Status and Errors

Summarize the validation results and identify broken or unsupported links.

In [8]:
summary = {
    'total_links': len(links_df),
    'invalid_format': sum(1 for row in valid_links if not row['valid_format']),
    'external_links': len(external_links),
    'broken_external': sum(1 for row in results if row['status_code'] not in (None, 200)),
}
summary, results_df[results_df['status_code'] != 200].head(50)

({'total_links': 178,
  'invalid_format': 0,
  'external_links': 7,
  'broken_external': 4},
                                               source  \
 0        docs\Physics Note\CMP\Reciprocal Lattice.md
 3               docs\Physics Note\Master's degree.md
 4               docs\Physics Note\Master's degree.md
 6  docs\Physics Note\RLI Astronomy (Mass of Jupit...

                                               target  valid_format reason  \
 0  https://www.researchgate.net/post/What-is-the-...          True
 3  https://www.dur.ac.uk/departments/academic/phy...          True
 4  https://www.ox.ac.uk/admissions/graduate/cours...          True
 6   https://doi.org/10.1111/j.1365-2966.2011.18947.x          True

    status_code
 0          403
 3          403
 4          403
 6          403  )

In [9]:
# Direct internal Markdown link validation for docs/
from pathlib import Path
import re

root = Path('.').resolve()
docs_root = root / 'docs'
md_files = sorted(docs_root.rglob('*.md'))
link_re = re.compile(r'!?\[[^\]]*\]\(([^)]+)\)')

broken = []
for md in md_files:
    text = md.read_text(encoding='utf-8', errors='ignore')
    for match in link_re.finditer(text):
        target = match.group(1).strip()
        if not target or target.startswith('#'):
            continue
        if any(target.startswith(p) for p in ('http://', 'https://', 'mailto:', 'javascript:')):
            continue
        if target.startswith('/'):
            broken.append((md.relative_to(root).as_posix(), target, 'absolute path'))
            continue
        target_file = target.split('#', 1)[0]
        if not target_file:
            continue
        target_path = (md.parent / target_file).resolve()
        if target_path.is_dir():
            if not (target_path / 'index.md').exists():
                broken.append((md.relative_to(root).as_posix(), target, 'dir without index'))
            continue
        if not target_path.exists():
            broken.append((md.relative_to(root).as_posix(), target, 'missing file'))

print('Internal docs links checked:', sum(1 for md in md_files for _ in link_re.finditer(md.read_text(encoding="utf-8", errors="ignore"))))
print('Broken internal docs links found:', len(broken))
for md, target, reason in broken[:200]:
    print(f'{md}: {target} -> {reason}')

Internal docs links checked: 178
Broken internal docs links found: 139
docs/Condensed Matter Physics.md: Physics%20Note/CMP/Lattice%20Type.md -> missing file
docs/Condensed Matter Physics.md: Physics%20Note/CMP/Lattice%20structure.md -> missing file
docs/Condensed Matter Physics.md: Physics%20Note/CMP/Reciprocal%20Lattice.md -> missing file
docs/Condensed Matter Physics.md: Physics%20Note/CMP/X-ray%20Diffraction.md -> missing file
docs/Condensed Matter Physics.md: Physics%20Note/CMP/Bonding.md -> missing file
docs/Condensed Matter Physics.md: Physics%20Note/CMP/Lattice%20vibration.md -> missing file
docs/Condensed Matter Physics.md: Physics%20Note/CMP/Heat%20Capacity.md -> missing file
docs/Condensed Matter Physics.md: Physics%20Note/Debye%20Model%201.md -> missing file
docs/Condensed Matter Physics.md: Physics%20Note/Metal%201.md -> missing file
docs/Condensed Matter Physics.md: Physics%20Note/Metal%20II.md -> missing file
docs/Condensed Matter Physics.md: Physics%20Note/Properties%20of%20free%20electron%20model%20(continuous -> missing file
docs/Condensed Matter Physics.md: Physics%20Note/Band%20Theory.md -> missing file
docs/Condensed Matter Physics.md: Physics%20Note/Bloch's%20theorem.md -> missing file
docs/Condensed Matter Physics.md: Physics%20Note/Introduction%20and%20Bonding.md -> missing file
docs/Condensed Matter Physics.md: Physics%20Note/Length%20Scales%20and%20Time%20Scales.md -> missing file
docs/Condensed Matter Physics.md: Physics%20Note/Lattices%20and%20Symmetry%20Operations.md -> missing file
docs/Condensed Matter Physics.md: Physics%20Note/Reading%20Character%20Tables.md -> missing file
docs/Condensed Matter Physics.md: Physics%20Note/Selection%20Rules%20and%20Properties%20of%20Broken%20Symmetry.md -> missing file
docs/Condensed Matter Physics.md: Physics%20Note/Crystallographic%20Space%20Groups.md -> missing file
docs/Condensed Matter Physics.md: Physics%20Note/Scattering%20Techniques.md -> missing file
docs/Condensed Matter Physics.md: Physics%20Note/Measuring%20Phonons.md -> missing file
docs/Condensed Matter Physics.md: Physics%20Note/Phonon%20Dispersion%20Curves.md -> missing file
docs/Condensed Matter Physics.md: Physics%20Note/Soft%20Modes%20and%20Displacive%20Phase%20Transition.md -> missing file
docs/Condensed Matter Physics.md: Physics%20Note/Semiconductor%20Physics.md -> missing file
docs/Condensed Matter Physics.md: Physics%20Note/Electronic%20Transition%20In%20Semiconductors.md -> missing file
docs/Condensed Matter Physics.md: Physics%20Note/Landau%20Theory%20Of%20Phase%20Transition.md -> missing file
docs/Condensed Matter Physics.md: Physics%20Note/Stability%20and%20Rigidity.md -> missing file
docs/Condensed Matter Physics.md: Physics%20Note/Dimensionality%20and%20Critical%20Exponents.md -> missing file
docs/Condensed Matter Physics.md: Physics%20Note/Superfluidity.md -> missing file
docs/Condensed Matter Physics.md: Physics%20Note/Classical%20Fluids.md -> missing file
docs/Condensed Matter Physics.md: Physics%20Note/Excitation.md -> missing file
docs/Condensed Matter Physics.md: Physics%20Note/Experimental%20Significance%20and%20Particles.md -> missing file
docs/Condensed Matter Physics.md: Physics%20Note/Amplitude%20Mode%20Excitation.md -> missing file
docs/Condensed Matter Physics.md: Physics%20Note/Mass%20of%20Excitation.md -> missing file
docs/Condensed Matter Physics.md: Physics%20Note/Domain%20Wall%20and%20Vortices%20in%20Superfluid.md -> missing file
docs/Condensed Matter Physics.md: Physics%20Note/Kink%20and%20Topological%20Objects.md -> missing file
docs/Condensed Matter Physics.md: Physics%20Note/Superfluid%20and%20Superconductivity.md -> missing file
docs/Condensed Matter Physics.md: Physics%20Note/Gauge%20Theory%20and%20Higgs%20Mechanism.md -> missing file
docs/Condensed Matter Physics.md: ../Physics Note/Physics/Introduction to Soft Condensed Matter Physics.md -> missing file
docs/Condensed Matter Physics.md: ../Physics Note/Surfaces and Interfaces 1.md -> missing file
docs/Condensed Matter Physics.md: ../Physics Note/Surfaces and Interfaces 2.md -> missing file
docs/Condensed Matter Physics.md: ../Physics Note/Mixtures 1 - Regular Solution Model.md -> missing file
docs/Condensed Matter Physics.md: ../Physics Note/Mixtures II - Stability and Phase Diagram.md -> missing file
docs/Condensed Matter Physics.md: ../Physics Note/Polymer - Introduction.md -> missing file
docs/Condensed Matter Physics.md: ../Physics Note/Polymer - Application.md -> missing file
docs/Condensed Matter Physics.md: ../Physics Note/Self-assembly - Aggregates, Micelles, Bilayers.md -> missing file
docs/Condensed Matter Physics.md: ../Physics Note/Colliods I - Single colloids and van der Waals interactions.md -> missing file
docs/Condensed Matter Physics.md: ../Physics Note/Colliods II - Double layer forces and the DLVO theory.md -> missing file
docs/Condensed Matter Physics.md: ../Physics Note/Liquid Crystals I - Introduction and Fundamental Concepts.md -> missing file
docs/Condensed Matter Physics.md: ../Physics Note/Liquid Crystal II - Phase Transitions and Elasticity.md -> missing file
docs/Condensed Matter Physics.md: ../Physics Note/Fundamental Equations for Magnetism.md -> missing file
docs/Condensed Matter Physics.md: ../Physics Note/Hund's Rule.md -> missing file
docs/Condensed Matter Physics.md: ../Physics Note/Diamagnetism.md -> missing file
docs/Condensed Matter Physics.md: ../Physics Note/Paramagnetism.md -> missing file
docs/Condensed Matter Physics.md: Physics%20Note/Exchange%20Interaction%20and%20Ferromagnetism.md -> missing file
docs/Condensed Matter Physics.md: Physics%20Note/Antiferromagnetism%20and%20Anisotropy.md -> missing file
docs/Condensed Matter Physics.md: ../Physics Note/Magnon.md -> missing file
docs/Condensed Matter Physics.md: ../Physics Note/Magnetic Domain.md -> missing file
docs/Condensed Matter Physics.md: ../Physics Note/Magnetism in Metals.md -> missing file
docs/Condensed Matter Physics.md: ../Physics Note/Band Gaps In Semiconductors.md -> missing file
docs/Condensed Matter Physics.md: ../Physics Note/Electrons and Holes In Semiconductors.md -> missing file
docs/Condensed Matter Physics.md: ../Physics Note/Statistical Mechanics for Semiconductors and Intrinsic Semiconductors.md -> missing file
docs/Condensed Matter Physics.md: ../Physics Note/Extrinsic Semiconductors.md -> missing file
docs/Condensed Matter Physics.md: ../Physics Note/PN Junction - Equilibrium.md -> missing file
docs/Condensed Matter Physics.md: Physics%20Note/PN%20Junction%20-%20Non-Equilibrium.md -> missing file
docs/Condensed Matter Physics.md: Physics%20Note/Introduction%20To%20Dielectrics.md -> missing file
docs/Condensed Matter Physics.md: Physics%20Note/Dielectric%20Function.md -> missing file
docs/Condensed Matter Physics.md: ../Physics Note/Ginzburg-Landau Theory of Ferroelectrics.md -> missing file
docs/Condensed Matter Physics.md: Physics%20Note/Introduction%20to%20Superconductivity.md -> missing file
docs/Condensed Matter Physics.md: Physics%20Note/Meissner%20Effect.md -> missing file
docs/Condensed Matter Physics.md: Physics%20Note/Ginzburg-Landau%20Theory%20For%20Superconductivity.md -> missing file
docs/Condensed Matter Physics.md: Physics%20Note/Condensation%20Energy%20and%20Magnetic%20Energy.md -> missing file
docs/Condensed Matter Physics.md: ../Physics Note/Home.md -> missing file
docs/Condensed Matter Physics.md: ../Physics Note/Courses.md -> missing file
docs/Modern Optical and Atomic Physics.md: Physics Note/Examples of Cartesian Separability (and non-separable -> missing file
docs/Nuclear and Particle Physics.md: ../Physics Note/Exchange Operators and Pauli Exclusion Principle.md -> missing file
docs/Physics Note/Fraunhofer diffraction as Fourier transform 1.md: u,v -> missing file
docs/Physics Note/Fraunhofer diffraction as Fourier transform.md: u,v -> missing file
docs/Physics Note/Frequency-Time Fourier Pairs and Mode Locked Pulse Trains.md: \omega -> missing file
docs/Physics Note/Fundamental and FT of common functions.md: u -> missing file
docs/Physics Note/Fundamental and FT of common functions.md: u -> missing file
docs/Physics Note/Fundamental and FT of common functions.md: u -> missing file
docs/Physics Note/Fundamental and FT of common functions.md: u,v -> missing file
docs/Physics Note/Introduction to Lasers and Cavities.md: u, v -> missing file
docs/Physics Note/Properties of FT.md: u -> missing file
docs/Physics Note/Properties of FT.md: u -> missing file
docs/Physics Note/Properties of FT.md: u -> missing file
docs/Physics Note/Properties of FT.md: u,v -> missing file
docs/Physics Note/Properties of FT.md: u, v -> missing file
docs/Physics Note/Temporal Coherence, Visibility and Normalised Autocorrelation Function.md: \omega -> missing file
docs/Quantum Mechanics.md: ../Physics Note/Basics of Quantum Mechanics.md -> missing file
docs/Quantum Mechanics.md: ../Physics Note/Operators and Expectation Values.md -> missing file
docs/Quantum Mechanics.md: ../Physics Note/The origin of uncertainty and other key results.md -> missing file
docs/Quantum Mechanics.md: ../Physics Note/The Schrodinger equation and eigenfunctions.md -> missing file
docs/Quantum Mechanics.md: ../Physics Note/Eigenfunctions versus superpositions.md -> missing file
docs/Quantum Mechanics.md: ../Physics Note/Superposition of eigenstates and transitions.md -> missing file
docs/Quantum Mechanics.md: ../Physics Note/Eigenfunctions of various potential.md -> missing file
docs/Quantum Mechanics.md: ../Physics Note/The 3D Schrodinger Equation.md -> missing file
docs/Quantum Mechanics.md: ../Physics Note/Angular Momentum.md -> missing file
docs/Quantum Mechanics.md: ../Physics Note/Angular momentum and spherical harmonics.md -> missing file
docs/Quantum Mechanics.md: ../Physics Note/Finding the Hydrogen Wavefunction.md -> missing file
docs/Quantum Mechanics.md: ../Physics Note/Generalising angular momentum.md -> missing file
docs/Quantum Mechanics.md: ../Physics Note/Spin.md -> missing file
docs/Quantum Mechanics.md: ../Physics Note/Time-independent perturbation theory.md -> missing file
docs/Quantum Mechanics.md: ../Physics Note/Degenerate perturbation theory.md -> missing file
docs/Quantum Mechanics.md: ../Physics Note/Degenerate perturbation theory II.md -> missing file
docs/Quantum Mechanics.md: ../Physics Note/Degenerate perturbation theory and hydrogen.md -> missing file
docs/Quantum Mechanics.md: ../Physics Note/Degenerate perturbation theory and hydrogen II.md -> missing file
docs/Quantum Mechanics.md: ../Physics Note/Hydrogen fine structure.md -> missing file
docs/Quantum Mechanics.md: ../Physics Note/Theorems and Principles.md -> missing file
docs/Quantum Mechanics.md: ../Physics Note/von Neumann's Axioms and Pauli Matrices.md -> missing file
docs/Quantum Mechanics.md: ../Physics Note/Magnetic Moment and Spin.md -> missing file
docs/Quantum Mechanics.md: ../Physics Note/Gauge Freedom I.md -> missing file
docs/Quantum Mechanics.md: ../Physics Note/Gauge Freedom II.md -> missing file
docs/Quantum Mechanics.md: ../Physics Note/Rayleigh-Ritz Variational Principle.md -> missing file
docs/Quantum Mechanics.md: ../Physics Note/Exchange Operators and Pauli Exclusion Principle.md -> missing file
docs/Quantum Mechanics.md: ../Physics Note/Consequences of Symmetry Properties of Wave Functions.md -> missing file
docs/Quantum Mechanics.md: ../Physics Note/Spins State in Symmetry Properties of Wave Functions.md -> missing file
docs/Quantum Mechanics.md: ../Physics Note/Many Electron Systems.md -> missing file
docs/Quantum Mechanics.md: ../Physics Note/Time-Dependent Schrodinger Equation.md -> missing file
docs/Quantum Mechanics.md: ../Physics Note/Perturbation Theory.md -> missing file
docs/Quantum Mechanics.md: ../Physics Note/Excitation of Electrons via Electromagnetic Field - Absorption and Stimulated Emission.md -> missing file
docs/Quantum Mechanics.md: ../Physics Note/Transition Rate - Einstein Coefficient.md -> missing file
docs/Quantum Mechanics.md: ../Physics Note/Selection Rules and Fermi's Golden Rule.md -> missing file
docs/Thermal Physics.md: ../Physics Note/Introduction, heat and temperature.md -> missing file
docs/Thermal Physics.md: ../Physics Note/Relevant Mathematics.md -> missing file
docs/Thermal Physics.md: ../Physics Note/Work and Internal Energy.md -> missing file
docs/Thermal Physics.md: ../Physics Note/Heat Engines and the Carnot cycle.md -> missing file
docs/Thermal Physics.md: ../Physics Note/2nd Law of Thermodynamics.md -> missing file
docs/Thermal Physics.md: ../Physics Note/Entropy and real engines.md -> missing file
docs/Thermal Physics.md: ../Physics Note/Thermodynamic potentials.md -> missing file
docs/Thermal Physics.md: ../Physics Note/Maxwell's relations and thermodynamic problem solving.md -> missing file
docs/Thermal Physics.md: ../Physics Note/Entropy Applications available work.md -> missing file
docs/Thermal Physics.md: ../Physics Note/Phase diagrams and phase transitions.md -> missing file
docs/Thermal Physics.md: ../Physics Note/Thermodynamics of real systems.md -> missing file
docs/Thermal Physics.md: ../Physics Note/Third Law of Thermodynamics.md -> missing file
docs/Thermal Physics.md: ../Physics Note/Introduction to statistical thermodynamics.md -> missing file
docs/Thermal Physics.md: ../Physics Note/Statistical thermodynamics.md -> missing file
docs/Thermal Physics.md: ../Physics Note/Overview.md -> missing file